version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: groovra-redis
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: groovra-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  auth-service:
    build:
      context: .
      dockerfile: Groovra.Auth.Microservice/Dockerfile
    container_name: groovra-auth
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - Jwt__Key=${JWT_SECRET_KEY}
      - Email__Host=sandbox.smtp.mailtrap.io
      - Email__Port=2525
      - Email__Username=${MAIL_USER}
      - Email__Password=${MAIL_PASS}
      - Authentication__Google__ClientId=${GOOGLE_CLIENT_ID}
      - Authentication__Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - Cors__AllowedOrigins__0=http://localhost:5178
      - Cors__AllowedOrigins__1=https://groovra-frontend.vercel.app
    depends_on:
      - rabbitmq
      - redis

  music-service:
    build:
      context: .
      dockerfile: Groovra.Music.Microservice/Dockerfile
    container_name: groovra-music
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - AllowedHosts=*
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - AuthGrpcUrl=http://auth-service:8080
      - JamendoApi__BaseUrl=https://api.jamendo.com/v3.0
      - JamendoApi__ClientId=16efb5ab
      - MediaStorage__BasePath=/app/media
    volumes:
      - groovra-media-volume:/app/media
    depends_on:
      - rabbitmq
      - redis
      - auth-service

  history-service:
    build:
      context: .
      dockerfile: Groovra.History.Microservice/Dockerfile
    container_name: groovra-history
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=${DB_CONNECTION_STRING}
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=guest
      - RabbitMQ__Password=guest
      - MusicGrpcUrl=http://music-service:8080
    depends_on:
      - rabbitmq
      - music-service

  gateway:
    build:
      context: .
      dockerfile: Groovra.ApiGateway/Dockerfile
    container_name: groovra-gateway
    ports:
      - "80:8080"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Jwt__Key=${JWT_SECRET_KEY}
      - Jwt__Issuer=groovra.local
      - Jwt__Audience=groovra.clients
      # Обрати внимание на точное совпадение с именами кластеров из appsettings.json и порты :8080
      - ReverseProxy__Clusters__auth-cluster__Destinations__auth-destination__Address=http://auth-service:8080
      - ReverseProxy__Clusters__music-cluster__Destinations__music-destination__Address=http://music-service:8080
      - ReverseProxy__Clusters__history-cluster__Destinations__history-destination__Address=http://history-service:8080
    depends_on:
      - auth-service
      - music-service
      - history-service

volumes:
  groovra-media-volume: